### ISSUE TITLE
Support for generics?

### ISSUE THREAD

**Issue by k1ngcyk** [ProbablyClem/utoipauto#15]
In utoipa we can do like:
```rust
#[derive(ToSchema)]
#[aliases(
    FooA = Foo<A>,
    FooB = Foo<B>
)]
pub struct Foo<T> {
    bar: T,
}
```
and generates two schema `FooA` and `FooB`,

and utoipauto has compile error with:
```rust
error[E0107]: missing generics for struct `Foo`
   --> src/mod.rs:123:5
    |
123 |     #[utoipauto]
    |     ^^^^^^^^^^^^ expected 1 generic argument
    |
note: struct defined here, with 1 generic parameter: `T`
   --> src/foo.rs:12:12
    |
12  | pub struct Foo<T> {
    |            ^^^^^^^^^^^ -
    = note: this error originates in the attribute macro `utoipauto` (in Nightly builds, run with -Z macro-backtrace for more info)
help: add missing generic argument
    |
123 |     #[utoipauto]<T>
    |                 +++
```

**Comment by EinarasGar** [comment]
Would like to see generics supported too. Otherwise, amazing crate!

**Comment by DenuxPlays** [comment]
I need this feature!
I tried to add #[utoipa_ignore] and add the schema manually but that didn't worked.

**Comment by DenuxPlays** [comment]
I am goind to try to solve this.
But give me a few days as this is my first time dealing with macros (let alone generic macros)

**Comment by ProbablyClem** [comment]
That would be a nice feature.
However, #[utoipa_ignore] works for me, even with generics. Have you tried restarting rust analyzer? Can you give me a minimal reproducible example ? @DenuxPlays

**Comment by DenuxPlays** [comment]
> That would be a nice feature.
> 
> However, #[utoipa_ignore] works for me, even with generics. Have you tried restarting rust analyzer? Can you give me a minimal reproducible example ? @DenuxPlays 

No it works just fine.
It was actually my code that made it look like it was the macros.

Also I have a plan which (if it works) would made the implementation of this feature very easy but I have to work on it tomorrow.

**Comment by ProbablyClem** [comment]
For the aliases features, you don't actually have to worry about generics.
You can have a look at the parse_from_attr function, that's where the fix will probably be.

You can see that it's where we look at struct's macros.
You'll need to search for the aliases macro, and return `DiscoverType::Model()` or `DiscoverType::Response()` with the names defined within the aliases macros, instead of the actual generic struct name.

You'll need to learn a bit about the syn crate, but otherwise it shouldn't be that hard, and you'll learn a lot !

Feel free to ask if you have any struggles or questions, I'll do my best to help.
Have fun !

**Comment by DenuxPlays** [comment]
> For the aliases features, you don't actually have to worry about generics.
> 
> You can have a look at the parse_from_attr function, that's where the fix will probably be.
> 
> 
> 
> You can see that it's where we look at struct's macros.
> 
> You'll need to search for the aliases macro, and return `DiscoverType::Model()` or `DiscoverType::Response()` with the names defined within the aliases macros, instead of the actual generic struct name.
> 
> 
> 
> You'll need to learn a bit about the syn crate, but otherwise it shouldn't be that hard, and you'll learn a lot !
> 
> 
> 
> Feel free to ask if you have any struggles or questions, I'll do my best to help.
> 
> Have fun !

That's what I thought but thank you for the information.
I think I can do this and I'll open a pr soon

**Comment by ProbablyClem** [comment]
I think we could have some, just like models

**Comment by DenuxPlays** [comment]
> I think we could have some, just like models

But here is no aliases macro for Response

**Comment by DenuxPlays** [comment]
> I think we could have some, just like models

I acutally have a question.
This my current progress..
```rs
if meta.path().is_ident("aliases") {
            println!("{:?}\n", meta);
        }
```

I cannot figure out on how to acces the inside of the aliases macro.
Can you help me with that?

**Comment by ProbablyClem** [comment]
I can't really help you without implementing it mysef... Take a look at the syn crate

**Comment by DenuxPlays** [comment]
> I can't really help you without implementing it mysef... Take a look at the syn crate

Ah okay
Gonna do this something has to work lol

**Comment by ProbablyClem** [comment]
Hey, support for generics got added in the new 0.1.10 release.
Thanks @DenuxPlays

**Comment by DenuxPlays** [comment]
> Hey, support for generics got added in the new 0.1.10 release.
> 
> Thanks @DenuxPlays 

If there are any bugs reported you can assign me.
I can maintain this feature if needed
