### ISSUE TITLE
Add partial import support & Stabilizing `generic_full_path` feature

### ISSUE THREAD

**Issue by DenuxPlays** [ProbablyClem/utoipauto#20]
## Adding last missing feature

Add support for partial imports.
This is the last feature that we are missing and when this is implemented I think we can mark `generic_full_path` as stable.

## Stabilizing the feature

I've now used the feature since I developed it and I have to say there isn't a case where it fails.
I do not know if someothers haved used so it would be great if someone could share their experience with it.

But I was sadly right about longer compile times and higher RAM usage.
The higher RAM usage can cause problems especially on PCs with a low amount of RAM. (8GB or less).

We cannot get rid of the higher RAM usage as we simply need to store more infromation.
Same with the disk usage we need to parse more to get the extra information needed.

I think we can say that this feature is stable.
But maybe you/others disagree or you miss some features.

Or maybe we should wait until the rust released they parallel front-end (see [here](https://blog.rust-lang.org/2023/11/09/parallel-rustc.html)) because this could potentially increase our RAM usage even more.
We have to test that though.

**Comment by ProbablyClem** [comment]
I haven't used it, but good to hear that it works :+1: 
I think we could mark it as stable, since it's not less tested than the rest of the crate...

It's behind a feature flag anyway so ne big deal.
You can submit a PR to update a readme since that's the only change :smile:

**Comment by DenuxPlays** [comment]
> I haven't used it, but good to hear that it works 👍 I think we could mark it as stable, since it's not less tested than the rest of the crate...
> 
> It's behind a feature flag anyway so ne big deal. You can submit a PR to update a readme since that's the only change 😄

Okay
I'll planed to add support for partial imports since that is the only thing that we currently not support.
I think I submit a pr (when I find time for it) and then mark it at stable.
I'll update this issue accordingly
