### ISSUE TITLE
Customize reported path

### ISSUE THREAD

**Issue by jssblck** [ProbablyClem/utoipauto#26]
Hey, awesome library! In #2, a user asked to have full paths reported; but I want the opposite: I want to be able to customize the path so that the full thing isn't reported.

For example, if I add paths manually, this works- but I don't see a way to both auto-discover _and_ not have the full path displayed.

In the below example (using `Scalar` to render the docs), the main `ApiDoc` is configured like so:
```rust
// Note: the below code snippet is inside `crate::api`.

#[utoipauto] // <-- This autodiscovers `crate::api::v1::ping`
#[derive(OpenApi)]
#[openapi(info(description = include_str!("../README.md")), paths(
    v0::health::handle, // <-- This is also autodiscovered, but overridden
))]
struct ApiDoc;
```

The manually added route correctly (for my preferences anyway) appears relative, but the autodiscovered one has the full path; I'm wondering if there's a way to override this behavior to make the path relative.

<img width="240" alt="Screenshot 2024-05-16 at 4 41 58 PM" src="https://github.com/ProbablyClem/utoipauto/assets/55713231/1bb6666d-c06f-437b-8b89-bcb54914b714">

Thanks for your time!

**Comment by DenuxPlays** [comment]
Maybe not your solution but I ordered my routes into tags.
This also allows you to add a basic description.

Works for me but maybe not for you.

**Comment by DenuxPlays** [comment]
@ProbablyClem Do we want to support something like this?

I think its doable.
We could resolve the imports and then only apply the diff.
When I impot this:
```rust
use  crate::api::*
```
And I have a struct at `crate::api::v1::Struct1` then we only could import it like this `v1::Struct1` but I am not sure if we want to do this.

**Comment by ProbablyClem** [comment]
Hmm it feels a bit weird...
Honestly, if there's another use case than just the display name why not, but otherwise I think most people use tags anyway.
I'm not totally against the idea, I'm just not sure if the added complexity is worth it....

**Comment by DenuxPlays** [comment]
Totally agree

I think we shouldn't implement it.
I wouldn't implement it unless there are other good reasons or more interest from others. 

If you agree this can closed right?
