### ISSUE TITLE
Need for maintainers

### ISSUE THREAD

**Issue by ProbablyClem** [ProbablyClem/utoipauto#28]
TLDR : I'll keep maintaining this crate but I need more people

Hey,
Since this crate as been growing in popularity, we've had more and more features request, and I can't keep up.
If you have an issue or feature request, feel free to submit an issue and a PR.
And if you'd like to get more involved in the maintenance of this crate, please answer to this issue or contact me at clement.guiton.dev@gmail.com

Thanks to everyone involved in the growth of this project

**Comment by DenuxPlays** [comment]
Hey,
as we use this library in our own project I could help maintain this project.
I already implemented the generic support feature which works really well (at least for me).

**Comment by ProbablyClem** [comment]
Thanks for your valuable contribution.
I've sent you an invite
