### ISSUE TITLE
Does discovery account for dash / underscore difference in path vs module name?

### ISSUE THREAD

**Issue by r0ck37c0d3r** [ProbablyClem/utoipauto#37]
I have a module, part of a workspace: this is its `Cargo.toml`
```toml
[package]
name = "child-mod"
```

It's a submodule of `current-crate` where I'm generating Openapi docs.

```
current-crate/
├─ src/
│  ├─ mod.rs
│  ├─ child-mod/
│  │  ├─ src/
│  │  │  ├─ models.rs
```

Hence, I need to both declare 
- current crate (because it's part of the workspace) - that part works fine ✅
- the submodule with `from` keyword, as specified [here](https://docs.rs/crate/utoipauto/latest), like this:

```
#[utoipauto(paths = "./current-crate/src,./src/models.rs from child-mod")]`
```

Problem is, importing from submodule looks like this (note `_` instead of `-`):

```rust
use child_mod::SomeStruct;
```

So you receive a file path in the macro and [transform it to module path](https://github.com/ProbablyClem/utoipauto/blob/main/utoipauto-core/src/file_utils.rs#L70). 

Also, you [recurse through the file tree](https://github.com/ProbablyClem/utoipauto/blob/main/utoipauto-core/src/discover.rs#L11) so I cannot directly input underscored file name in the `#[utoipauto(path` annotation because the file wouldn't be found.

However I couldn't find whether you account for this module naming quirk: difference between file paths containing `-` and module paths containing `_`. 

Is this why my `path` annotation isn't working or something else?

**Comment by ProbablyClem** [comment]
Interesting, I believe we just never encountered this case.
Adding a replace in [transform it to module path](https://github.com/ProbablyClem/utoipauto/blob/main/utoipauto-core/src/file_utils.rs#L70) should do the trick.
Feel free to submit a PR
