### ISSUE TITLE
Documentation improvement: Workspace usage

### ISSUE THREAD

**Issue by DenuxPlays** [ProbablyClem/utoipauto#9]
I just keep getting this error:
![image](https://github.com/ProbablyClem/utoipauto/assets/83671398/74c33bc2-d0a5-4b7e-abb6-759ed7569565)

Here is the code that produces the error:
```rs
#[utoipauto(
	paths = "./src/controller/user.rs"
)]
#[derive(OpenApi)]
#[openapi(modifiers(&SecurityAddon))]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
	fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
		match openapi.components {
			Some(_) => {}
			None => {
				openapi.components = Some(Components::default());
			}
		}
		openapi.components.as_mut().unwrap();
	}
}
```
Everything works fine when adding paths manually like utoipa intended.

**Comment by DenuxPlays** [comment]
Code can also be found here: https://github.com/financrr/backend/tree/main/backend

**Comment by DenuxPlays** [comment]
Found the error:
Workspaces...
Please add support for it.
There is a "work-around":

Instead of doing "./src/controller/" you have to do "./backend/src/controller"

**Comment by ProbablyClem** [comment]
Hey, thanks for your feedback.
I don't think they'll be a fix, since it's not really an issue.
You have to specify the right path for it to work.

However, we probably need a documentation improvement to clarify this behaviour.

**Comment by DenuxPlays** [comment]
> Hey, thanks for your feedback. I don't think they'll be a fix, since it's not really an issue. You have to specify the right path for it to work.
> 
> However, we probably need a documentation improvement to clarify this behaviour.

I can take care of this.
